name = "Saturn"
uuid = "ba7cab78-9a66-4425-b90d-0d9eaa35973e"
version = "0.1.0"
authors = ["Francesco Mandunzio <f.mandunzio@campus.unimib.it>"]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
CSV = "1.1.0"
DataFrames = "1.8.2"
LinearAlgebra = "1.12.0"
Statistics = "1.11.5"
